version: "3.3"

services:
  docker-web:
    network_mode: bridge
    depends_on:
      - docker-timetable
      - docker-allocation
      - docker-addcredits
    build:
      context: ./Web
    container_name: web-timetable
    ports:
      - 8070:8070

  docker-addcredits:
    network_mode: bridge
    build:
      context: ./AddCredits
    container_name: microservice-addcredits
    ports:
      - 8071:8071

  docker-allocation:
    network_mode: bridge
    build:
      context: ./Allocation
    container_name: microservice-allocation
    ports:
      - 8072:8072
  docker-timetable:
    network_mode: bridge
    build:
      context: ./Timetable
    container_name: api-timetable
    ports:
      - 8073:8073
